# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Configure openSuSE machine
    config.vm.define "linux" do |linux|
      linux.vm.box = "generic/opensuse15"
      linux.vm.network "private_network", ip: "192.168.56.20"
      linux.vm.hostname = "virt-lin"
      linux.vm.synced_folder "data", "/vagrant"
      linux.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "2048"
        vb.cpus = 2
      end
      linux.vm.provision "shell", path: "data/vagrant-openSuSE.sh", privileged: "true"  
    end
    # Configure Windows machine
    config.vm.define "windows" do |windows|
      windows.vm.box = "gusztavvargadr/windows-10"
      windows.vm.network "private_network", ip: "192.168.56.10"
      windows.vm.hostname = "virt-win"
      windows.vm.synced_folder "data", "/vagrant"
      windows.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "4096"
        vb.cpus = 2
      end
      windows.vm.provision "shell", path: "data/vagrant-Win10sec.bat", privileged: "true"  
    end
end
